// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dizoouylsxirlxlwjflv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpem9vdXlsc3hpcmx4bHdqZmx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTM0NTUsImV4cCI6MjA2MTIyOTQ1NX0.jI9OekFoL4e-lPt6GcwvumQjMa4a2g5kotFR4BdssYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);